---
- name: Configurer le conteneur Docker
  hosts: localhost
  connection: local
  tasks:
    - name: Vérifier que Docker est installé
      package:
        name: docker-ce
        state: present

    - name: Démarrer le conteneur
      command: docker start myapp
      when: "'myapp' in docker_containers"
